server:
  port: 18080

spring:
  profiles:
    active: dev

  devtools:
    livereload:
      port: 35730    #热部署端口，默认是35729，手动设置避免在多个应用热部署时端口冲突
    restart:
      enabled: true
      additional-exclude: WEB-INF/**

  datasource:
    url: jdbc:mysql://localhost:3306/myblog?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root0
  jpa:
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    hibernate:
      ddl-auto: update

  thymeleaf:
    #配置模板引擎
    prefix: classpath:/templates/  #默认值
    suffix: .html   #默认值
    cache: false  #默认true
    #配置静态资源文件路径
  resources:
    static-locations: ["classpath:/META-INF/resources/","classpath:/resources/","classpath:/static/","classpath:/public/"]  #默认值

